### ISSUE TITLE
Опасная рекурсия

### ISSUE THREAD

**Issue by kernusr** [AlekVolsk/plg_content_loadmodid#1]
В html-модуле делаем вывод {loadmodid module_id}, в module_id указываем id этого же модуля (ну вот не внимательный такой юзер...) и сервер уходит в ступор из-за бесконечной рекурсии. 
Нужно подумать, над обработкой подобного исключения

**Comment by AlekVolsk** [comment]
плагин не знает, откуда он был вызван

**Comment by AlekVolsk** [comment]
К сожалению, вынужден закрыть этот вопрос как нерешаемый в настоящий момент: Joomla не даёт никакой информации, откуда именно был вызван плагин, кроме данных об активном пункте меню, из которого гипотетически можно вытянуть, опубликован ли вызываемый модуль на данной странице, но из него ли пришёл вызов - непонятно.

Возможно, в J4 что-то изменится к лучшему.

Кстати, этот же баг имеется и с штатном плагине Joomla.
